# Generated by Django 2.2.9 on 2020-01-29 16:04

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [("dashboard", "0143_zip_file_field")]

    operations = [
        migrations.AlterModelOptions(
            name="extractedchemical",
            options={
                "ordering": (
                    "-extracted_text_id",
                    "component",
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("ingredient_rank"),
                        nulls_last=True,
                    ),
                )
            },
        )
    ]
